### ISSUE TITLE
unable to calibrate with 0.6.8

### ISSUE THREAD

**Issue by nzjrs** [strawlab/flydra#32]
@etiennecampione  was unable to calibrate flycube8 using 0.6.8 as there were no points present in the h5 file, despite them being clearly visible in the image view. rolling back to 0.6.7 and not changing any other settings fixed the issue.

I don't think this is related to #30 as commenting out the logging code (both the service proxy on the camnode side, and the service on the mainbrain side) does not fix the bug.

this is in contrast with @maxlklaxl who has made several calibrations with 0.6.8 (although that was on ros-hydro)

**Comment by etiennecampione** [comment]
In case it might help, here some copy-pastes from what I get when I start the `roslaunch ./flycube_only_flydra_calib.launch --screen` (calibration - step 3: flydra calibration) with 0.6.8. I actually get different kinds of error messages (I can't say if they are related):

**Example 1:**
```
Exception in thread LogMessageSender:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 1041, in run
    self._main_brain.log_message(*log_message)
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 197, in log_message
    self._log_message(req)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 430, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 506, in call
    transport.send_message(request, self.seq)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_base.py", line 590, in send_message
    self.write_buff.truncate(0)
AttributeError: 'NoneType' object has no attribute 'truncate'
[...]
[FATAL] [WallTime: 1508149116.783246] ERROR: thread LogMessageSender died unexpectedly. Quitting
[INFO] [WallTime: 1508149116.783585] received log message from Basler_21426003:   Basler_21426003 frames apparently skipped: 52 (243 vs 190)
[FATAL] [WallTime: 1508149116.832617] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149116.873336] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149116.914018] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149116.954675] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149116.985257] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149116.985521] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149116.985715] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508149116.985901] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149116.986106] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[INFO] [WallTime: 1508149117.014890] triggerbox_client: waiting for clockmodel estimate
[flydra_camera_node-4] process has died [pid 4376, exit code 1].
log files: /home/strawlab/.ros/log/53ebd508-b25b-11e7-8244-bcee7bdac270/flydra_camera_node-4*.log
```

**Example 2:**
```
Exception in thread LogMessageSender:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 1041, in run
    self._main_brain.log_message(*log_message)
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 197, in log_message
    self._log_message(req)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 430, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 519, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

[INFO] [WallTime: 1508149196.186184]   handle_commands: key set
[INFO] [WallTime: 1508149196.189185] setting camera property expected_trigger_framerate=100.0
Exception in thread LogMessageSender:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 1041, in run
    self._main_brain.log_message(*log_message)
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 197, in log_message
    self._log_message(req)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 430, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 506, in call
    transport.send_message(request, self.seq)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_base.py", line 589, in send_message
    self.write_data(self.write_buff.getvalue())
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_base.py", line 613, in write_data
    raise TransportTerminated(str(errno)+msg)
TransportTerminated: 32Broken pipe

[INFO] [WallTime: 1508149196.191843] using slow method, calculated mean and sumsqf frames from first 20 frames
[INFO] [WallTime: 1508149196.192684] received log message from Basler_21425981: using cam_iface driver: mega (wrapper: ctypes)
Exception in thread LogMessageSender:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 1041, in run
    self._main_brain.log_message(*log_message)
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 197, in log_message
    self._log_message(req)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 430, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 511, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/flydra_mainbrain/log_message] returned no response
[...]
[FATAL] [WallTime: 1508149196.351144] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.377445] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.387781] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.398090] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.398283] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.398460] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.398635] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.398797] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.398958] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.399131] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.399284] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.399450] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.399625] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.399775] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.399943] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.400110] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.400258] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.400425] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508149196.400584] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[...]
[flydra_camera_node-4] process has died [pid 4916, exit code 1].
log files: /home/strawlab/.ros/log/8354d7b8-b25b-11e7-9271-bcee7bdac270/flydra_camera_node-4*.log
```

**Example 3:**
```
Exception in thread LogMessageSender:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 1041, in run
    self._main_brain.log_message(*log_message)
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 197, in log_message
    self._log_message(req)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 430, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 519, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

Exception in thread LogMessageSender:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 1041, in run
    self._main_brain.log_message(*log_message)
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 197, in log_message
    self._log_message(req)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 430, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 511, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/flydra_mainbrain/log_message] returned no response

Exception in thread LogMessageSender:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 1041, in run
    self._main_brain.log_message(*log_message)
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 197, in log_message
    self._log_message(req)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 430, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 522, in call
    transport.close()
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_base.py", line 761, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

Exception in thread LogMessageSender:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 1041, in run
    self._main_brain.log_message(*log_message)
  File "/usr/lib/python2.7/dist-packages/flydra/camnode.py", line 197, in log_message
    self._log_message(req)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 430, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/ros.electric.boost1.46/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 511, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/flydra_mainbrain/log_message] returned no response
[...]
[FATAL] [WallTime: 1508150187.879788] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.891928] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.892190] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.892396] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.892601] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.892771] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.892950] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.893159] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.893343] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.893499] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.893679] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.893871] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.894037] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.894210] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.894406] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[...]
[FATAL] [WallTime: 1508150187.879788] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.891928] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.892190] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.892396] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.892601] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.892771] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.892950] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.893159] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.893343] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.893499] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.893679] ERROR: thread save_small.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.893871] ERROR: thread cam_processor.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.894037] ERROR: thread LogMessageSender died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.894210] ERROR: thread save_cam.mainloop died unexpectedly. Quitting
[FATAL] [WallTime: 1508150187.894406] ERROR: thread save_small.mainloop died unexpectedly. Quitting

```
